# Generated by Django 5.1.7 on 2025-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_carrito_carritoproducto_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.TextField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
